usr = 'bits-certify'
db = 'ISP'
pwd = '7Ym4VfuhG28lNdeX'
MAX_CONTENT_ALLOWED = 16 * 1000 * 1000
UPLOAD_FOLDER = './crypto/uploads/'
SIGNED_FOLDER = './crypto/signed/'
ALLOWED_EXTENSIONS = {'txt', 'pdf'}
GNUPG_HOME_KUSHAL = '/home/kushal-joseph/.gnupg'
GNUPG_HOME_GARVIT = '/home/garvitsingh/.gnupg'